<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>peminjaman PDF</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    <style>
        /* Ensure styles print correctly */
        @media print {
            body {
                margin: 0;
            }
        }
    </style>
</head>
<body class="bg-white p-10">
    <!-- Header Section -->
    <div class="text-center mb-8">
        <h2 class="text-2xl font-bold">Surat peminjaman</h2>
        <hr class="my-4 border-gray-300">
    </div>

    <!-- peminjaman Info -->
    <div class="mb-8">
        <h3 class="text-xl font-semibold mb-2">Informasi peminjaman</h3>
        <div class="grid grid-cols-2 gap-4">
            <div>
                <p><strong>Nama Pengaju:</strong> {{ $peminjaman->user->name }}</p>
                <p><strong>Email:</strong> {{ $peminjaman->user->email }}</p>
                <p><strong>Telepon:</strong> {{ $peminjaman->user->phone }}</p>
            </div>
            <div>
                <p><strong>Matakuliah:</strong> {{ $peminjaman->matakuliah->name }}</p>
                <p><strong>Tanggal peminjaman:</strong> {{ Carbon\Carbon::parse($peminjaman->created_at)->format('Y-m-d') }}</p>
            </div>
        </div>
    </div>

    <!-- Loop through each Prasat -->
    @foreach ($peminjaman->prasat as $prasat)
        <div class="mb-8">
            <!-- Prasat Title and Date -->
            <h4 class="text-lg font-semibold mb-2">Prasat: {{ $prasat->nama_prasat }}</h4>
            <p class="text-gray-600 mb-4">Tanggal: {{ Carbon\Carbon::parse($prasat->created_at)->format('Y-m-d') }}</p>

            <!-- Table for BarangByPrasat -->
            <div class="overflow-hidden rounded-lg border border-gray-200">
                <table class="min-w-full divide-y divide-gray-200">
                    <thead class="bg-gray-50">
                        <tr>
                            <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">#</th>
                            <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Nama Barang</th>
                            <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Quantity (Qty)</th>
                        </tr>
                    </thead>
                    <tbody class="bg-white divide-y divide-gray-200">
                        @foreach ($prasat->barangByprasat as $barang)
                            <tr>
                                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">{{ $loop->iteration }}</td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{{ $barang->barang->nama_barang }}</td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{{ $barang->qty }}</td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    @endforeach

    <!-- Footer Section -->
    <div class="mt-8 text-center">
        <p class="text-sm text-gray-500">Generated by System | {{ Carbon\Carbon::now()->format('Y-m-d') }}</p>
    </div>
</body>
</html>
